//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadPencil.BatchMLPEncoder3 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainFormCodeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormCodeStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SadPencil.BatchMLPEncoder3.MainFormCodeStrings", typeof(MainFormCodeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The bit depth is incorrect. 的本地化字符串。
        /// </summary>
        internal static string CheckAndChangePropertiesBitDepthIncorrectString {
            get {
                return ResourceManager.GetString("CheckAndChangePropertiesBitDepthIncorrectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The duration is incorrect. 的本地化字符串。
        /// </summary>
        internal static string CheckAndChangePropertiesDurationIncorrectString {
            get {
                return ResourceManager.GetString("CheckAndChangePropertiesDurationIncorrectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name has already existed. 的本地化字符串。
        /// </summary>
        internal static string CheckAndChangePropertiesNameExistsString {
            get {
                return ResourceManager.GetString("CheckAndChangePropertiesNameExistsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name is illegal. 的本地化字符串。
        /// </summary>
        internal static string CheckAndChangePropertiesNameIllegalString {
            get {
                return ResourceManager.GetString("CheckAndChangePropertiesNameIllegalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The sampling rate is incorrect. 的本地化字符串。
        /// </summary>
        internal static string CheckAndChangePropertiesSamplingRateIncorrectString {
            get {
                return ResourceManager.GetString("CheckAndChangePropertiesSamplingRateIncorrectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eac3to can not convert this file. 的本地化字符串。
        /// </summary>
        internal static string CreateSsfFilesExceptionString {
            get {
                return ResourceManager.GetString("CreateSsfFilesExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        internal static string ExecuteReportsMessageString {
            get {
                return ResourceManager.GetString("ExecuteReportsMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string MainFormFormClosingCaptionString {
            get {
                return ResourceManager.GetString("MainFormFormClosingCaptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch MLP Encoder is processing now. Close anyway? 的本地化字符串。
        /// </summary>
        internal static string MainFormFormClosingTextString {
            get {
                return ResourceManager.GetString("MainFormFormClosingTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not click &quot;Encoder Options&quot; menu. 的本地化字符串。
        /// </summary>
        internal static string OpenSurcodeOptionsCannotClickEncoderOptionsMenuString {
            get {
                return ResourceManager.GetString("OpenSurcodeOptionsCannotClickEncoderOptionsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not expand &quot;Options&quot; menu. 的本地化字符串。
        /// </summary>
        internal static string OpenSurcodeOptionsCannotExpandOptionsMenuString {
            get {
                return ResourceManager.GetString("OpenSurcodeOptionsCannotExpandOptionsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find &quot;Encoder Options&quot; menu. 的本地化字符串。
        /// </summary>
        internal static string OpenSurcodeOptionsCannotFindEncoderOptionsMenuString {
            get {
                return ResourceManager.GetString("OpenSurcodeOptionsCannotFindEncoderOptionsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find &quot;Options&quot; menu. 的本地化字符串。
        /// </summary>
        internal static string OpenSurcodeOptionsCannotFindOptionsMenuString {
            get {
                return ResourceManager.GetString("OpenSurcodeOptionsCannotFindOptionsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You clicked the &quot; 的本地化字符串。
        /// </summary>
        internal static string Page2PropertyButtonClickMessageStringLeft {
            get {
                return ResourceManager.GetString("Page2PropertyButtonClickMessageStringLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; button manually. 的本地化字符串。
        /// </summary>
        internal static string Page2PropertyButtonClickMessageStringRight {
            get {
                return ResourceManager.GetString("Page2PropertyButtonClickMessageStringRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Page4BackgroundWorkerRunWorkerCompletedErrorString {
            get {
                return ResourceManager.GetString("Page4BackgroundWorkerRunWorkerCompletedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find eac3to. 的本地化字符串。
        /// </summary>
        internal static string Page5StartButtonClickCannotFindEac3toString {
            get {
                return ResourceManager.GetString("Page5StartButtonClickCannotFindEac3toString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find the output folder. 的本地化字符串。
        /// </summary>
        internal static string Page5StartButtonClickCannotFindOutputFolderString {
            get {
                return ResourceManager.GetString("Page5StartButtonClickCannotFindOutputFolderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find Surcode MLP Encoder. 的本地化字符串。
        /// </summary>
        internal static string Page5StartButtonClickCannotFindSurcodeString {
            get {
                return ResourceManager.GetString("Page5StartButtonClickCannotFindSurcodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find the temporary folder. 的本地化字符串。
        /// </summary>
        internal static string Page5StartButtonClickCannotFindTempFolderString {
            get {
                return ResourceManager.GetString("Page5StartButtonClickCannotFindTempFolderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing Directory 的本地化字符串。
        /// </summary>
        internal static string Page5StartButtonClickMissingDirectoryString {
            get {
                return ResourceManager.GetString("Page5StartButtonClickMissingDirectoryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing File 的本地化字符串。
        /// </summary>
        internal static string Page5StartButtonClickMissingFileString {
            get {
                return ResourceManager.GetString("Page5StartButtonClickMissingFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Question 的本地化字符串。
        /// </summary>
        internal static string Page6BackgroundWorkersRunWorkerCompletedErrorCaptionString {
            get {
                return ResourceManager.GetString("Page6BackgroundWorkersRunWorkerCompletedErrorCaptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 files haven&apos;t been converted to MLP files. Do you want to retry? 的本地化字符串。
        /// </summary>
        internal static string Page6BackgroundWorkersRunWorkerCompletedErrorTextString {
            get {
                return ResourceManager.GetString("Page6BackgroundWorkersRunWorkerCompletedErrorTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string Page6BackgroundWorkersRunWorkerCompletedSuccessCaptionString {
            get {
                return ResourceManager.GetString("Page6BackgroundWorkersRunWorkerCompletedSuccessCaptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All files have been converted to MLP files successfully. 的本地化字符串。
        /// </summary>
        internal static string Page6BackgroundWorkersRunWorkerCompletedSuccessTextString {
            get {
                return ResourceManager.GetString("Page6BackgroundWorkersRunWorkerCompletedSuccessTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Page6CancelButtonClickConfirmCaptionString {
            get {
                return ResourceManager.GetString("Page6CancelButtonClickConfirmCaptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to cancel? 的本地化字符串。
        /// </summary>
        internal static string Page6CancelButtonClickConfirmTextString {
            get {
                return ResourceManager.GetString("Page6CancelButtonClickConfirmTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eac3to hasn&apos;t exited yet. Time&apos;s out. 的本地化字符串。
        /// </summary>
        internal static string Page6eac3toBackgroundWorkerDoWorkEac3toTimeoutString {
            get {
                return ResourceManager.GetString("Page6eac3toBackgroundWorkerDoWorkEac3toTimeoutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eac3to is converting files... 的本地化字符串。
        /// </summary>
        internal static string Page6eac3toBackgroundWorkerDoWorkEac3toWorkingString {
            get {
                return ResourceManager.GetString("Page6eac3toBackgroundWorkerDoWorkEac3toWorkingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you get annoyed at eac3to&apos;s annoying sound, please delete &quot;success.wav&quot; and &quot;error.wav&quot; files in the eac3to folder. 的本地化字符串。
        /// </summary>
        internal static string Page6ListviewsSelectedIndexChangedDefaultTextString {
            get {
                return ResourceManager.GetString("Page6ListviewsSelectedIndexChangedDefaultTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not click &quot;Open&quot; button. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkCannotClickOpenButtonString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkCannotClickOpenButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not click &quot;Start&quot; button. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkCannotClickStartButtonString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkCannotClickStartButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not expand &quot;Open&quot; menu. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkCannotExpandOpenMenuString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkCannotExpandOpenMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not expand &quot;Setup&quot; menu. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkCannotExpandSetupMenuString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkCannotExpandSetupMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find &quot;Filename&quot; textbox. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkCannotFindFilenameString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkCannotFindFilenameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find &quot;Open&quot; button. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkCannotFindOpenButtonString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkCannotFindOpenButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find &quot;Open&quot; menu. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkCannotFindOpenMenuString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkCannotFindOpenMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find &quot;Setup&quot; menu. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkCannotFindSetupMenuString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkCannotFindSetupMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find &quot;Start&quot; button. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkCannotFindStartButtonString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkCannotFindStartButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eac3to can not convert this file. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkEac3toErrorString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkEac3toErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &quot;Open&quot; dialog hasn&apos;t appeared yet. Time&apos;s out. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkOpenDialogTimeoutString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkOpenDialogTimeoutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting Surcode MLP Encoder... 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkStartSurcodeString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkStartSurcodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surcode MLP Encoder can not convert this file. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkSurcodeFailedString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkSurcodeFailedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surcode MLP Encoder hasn&apos;t exited yet. Time&apos;s out. 的本地化字符串。
        /// </summary>
        internal static string Page6SurcodeBackgroundWorkerDoWorkSurcodeTimeoutString {
            get {
                return ResourceManager.GetString("Page6SurcodeBackgroundWorkerDoWorkSurcodeTimeoutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not start Surcode MLP Encoder. 的本地化字符串。
        /// </summary>
        internal static string RunSurcodeFailedString {
            get {
                return ResourceManager.GetString("RunSurcodeFailedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time&apos;s out. 的本地化字符串。
        /// </summary>
        internal static string RunSurcodeTimeoutString {
            get {
                return ResourceManager.GetString("RunSurcodeTimeoutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing 的本地化字符串。
        /// </summary>
        internal static string SetMainFormTextString {
            get {
                return ResourceManager.GetString("SetMainFormTextString", resourceCulture);
            }
        }
    }
}
